clc;
clear all;
close all;
x=input('enter the first input sequence=');
h=input('enter the second input sequence=');
l=length(x);
m=length(h);
N=max(l,m);
Xk=fft(x,N);
Hk=fft(h,N);
Yk=Xk.*Hk;
y=ifft(Yk,N);
disp('circuler convoluted output using DFT and IDFT method');
disp(y);
subplot(3,1,1);
stem(x);
title('the first sequence');
xlabel('time');
ylabel('amplitude');
subplot(3,1,2);
stem(h);
title('the second sequence');
xlabel('time');
ylabel('amplitude');
subplot(3,1,3);
stem(y);
title('the circuler convoluted sequence');
xlabel('time');
ylabel('amplitude');
