% Create a dipole antenna
% Generated by MATLAB(R) 9.11 and Antenna Toolbox 5.1.
% Generated on: 11-Nov-2025 13:58:31

%% Antenna Properties 

antennaObject = design(dipole, 4000*1e3);
% Show
figure;
show(antennaObject) 

%% Antenna Analysis 
% Define plot frequency 
plotFrequency = 4*1e6;
% Define frequency range 
freqRange = (3600:40:4400)*1e3;
% impedance
figure;
impedance(antennaObject, freqRange)
% sparameter
figure;
s = sparameters(antennaObject, freqRange); 
rfplot(s)
% pattern
figure;
pattern(antennaObject, plotFrequency)
% azimuth
figure;
patternAzimuth(antennaObject, plotFrequency, 0, 'Azimuth', 0:5:360)
% elevation
figure;
patternElevation(antennaObject, plotFrequency,0,'Elevation',0:5:360)
% current
figure;
current(antennaObject, plotFrequency)

