% Create a yagiUda antenna
% Generated by MATLAB(R) 9.11 and Antenna Toolbox 5.1.
% Generated on: 11-Nov-2025 14:11:05

%% Antenna Properties 

antennaObject = design(yagiUda, 2652*1e6);
% Show
figure;
show(antennaObject) 

%% Antenna Analysis 
% Define plot frequency 
plotFrequency = 2.652*1e9;
% Define frequency range 
freqRange = (2386.8:26.52:2917.2)*1e6;
% impedance
figure;
impedance(antennaObject, freqRange)
% sparameter
figure;
s = sparameters(antennaObject, freqRange); 
rfplot(s)
% pattern
figure;
pattern(antennaObject, plotFrequency)
% azimuth
figure;
patternAzimuth(antennaObject, plotFrequency, 0, 'Azimuth', 0:5:360)
% elevation
figure;
patternElevation(antennaObject, plotFrequency,0,'Elevation',0:5:360)
% current
figure;
current(antennaObject, plotFrequency)

